### ISSUE TITLE
Is there any way to change the size of the image?

### ISSUE THREAD

**Issue by lwj0012** [metempsy/gem5_arm_fullsystem_files_generator#3]
Seems the default image size is 2GB, which is too small for some benchmarks. I didn't find a proper place to change...

**Comment by pcabre** [comment]
The Dockerfile is not creating any image, but just modifying the ones from http://www.gem5.org/dist/current/arm/aarch-system-2014-10.tar.xz, thus, the size of the generated images is the same as the original images.
I believe that the right way to fix this would be to add a mechanism to resize images in the https://gem5.googlesource.com/public/gem5/+/master/util/gem5img.py script
